---
title: "Assignment_2"
author: "Bin Feng"
output: pdf_document
---
```{r setup}
# include library
library(MASS)
library(glmnet)

#set seed to ensure reproducibility
set.seed(8259)
```

# Data Preparation
```{r}
myData = Boston
names(myData)[14] = "Y"
iLog = c(1, 3, 5, 6, 8, 9, 10, 14);
myData[, iLog] = log(myData[, iLog]);
myData[, 2] = myData[, 2] / 10;
myData[, 7] = myData[, 7]^2.5 / 10^4
myData[, 11] = exp(0.4 * myData[, 11]) / 1000;
myData[, 12] = myData[, 12] / 100;
myData[, 13] = sqrt(myData[, 13]);

X = as.matrix(myData[, -14])
y = myData$Y

lam.seq = c(0.30, 0.2, 0.1, 0.05, 0.02, 0.005)
```

```{r}
one_step_lasso = function(r, x, lam){
  xx = sum(x^2)
  xr = sum(r*x)
  b = (abs(xr) -lam/2)/xx
  b = sign(xr)*ifelse(b>0, b, 0)
  return(b)
}

MyLasso = function(X, y, lam.seq, maxit = 50, standardize = TRUE){
  # X: n-by-p design matrix without the intercept
  # y: n-by-1 response vector
  # lam.seq: sequence of lambda values
  # maxit: number of updates for each lambda
  # standardize: if True, center and scale X and y. 

  n = length(y)
  p = dim(X)[2]
  nlam = length(lam.seq)
  B = matrix(, nrow = nlam, ncol = p + 1)
  
  if(standardize==TRUE){
    # YOUR CODE
    # Center and scale X and y
    # Record the corresponding means and scales
    n = length(y)
    X.means = apply(X, 2, mean)
    X.sd = apply(X, 2, sd)*sqrt((n-1)/n)
    # remove mean and divided by sd for each column
    X = t((t(X) - X.means)/X.sd)  
    y.means = mean(y)
    y.sd = sd(y)*sqrt((n-1)/n)
    y = (y - y.means)/y.sd 
  }
  
  # Initilize coef vector b and residual vector r
  b = rep(0, p)
  r = y
  
  # Triple nested loop
  for(m in 1:nlam){
    lam = 2*n*lam.seq[m]/y.sd # assign lambda value
    for(step in 1:maxit){
      for(j in 1:p){
  
        r = r + (X[,j]*b[j])
        b[j] = one_step_lasso(r, X[, j], lam)
        r = r - X[, j] * b[j]
  
      }
    }
    B[m, -1] = b
  }

  if(standardize==TRUE){
      # YOUR CODE
      # scale back the coefficients and update the intercepts B[, 1]
    B[,-1] = t(t(B[,-1]) * y.sd / X.sd)
    B[,1] = t(y.means - colSums(t(B[,-1]) * X.means / X.sd)) # is this correct??
  }
  return(t(B))
}
```

```{r}
lam.seq = c(0.30, 0.2, 0.1, 0.05, 0.02, 0.005)
lasso.fit = glmnet(X, y, alpha = 1, lambda = lam.seq)
coef(lasso.fit)

myout = MyLasso(X, y, lam.seq, maxit = 50)
rownames(myout) = c("Intercept", colnames(X))
myout
max(abs(coef(lasso.fit) - myout))
```