---
title: "Assignment_3_8259_binfeng2"
author: "Bin Feng"
output: pdf_document
---

```{r}
# include library
library(mclust)
```

```{r}
Estep <- function(data, G, para){
  # Your Code
  # return the n-by-G probability matrix
  pr = para$prob
  mu = para$mean
  inv = solve(para$Sigma)
  n = nrow(data)
  tmp = NULL
  for(k in 1:G){
    tmp = cbind(tmp, 
                 apply(data, 1, 
                       function(x) t(x - mu[, k]) %*% inv %*% (x - mu[, k])))
  }
  tmp = -tmp/2 + matrix(log(pr), nrow=n, ncol=G, byrow=TRUE)
  tmp = exp(tmp)
  tmp = tmp / apply(tmp, 1, sum)
  return(tmp)
}

Mstep <- function(data, G, para, post.prob){ 
  # Your Code
  # Return the updated parameters
  # update prob
  prob.new <- apply(post.prob, 2, sum) / nrow(post.prob)
  # update mean
  mean.new <- sweep(t(data) %*% post.prob, 2, apply(post.prob, 2, sum), '/')
  data = data.matrix(data)
  sigma.new = 0
  # update sigma
  for(i in 1:G){
    tmp = t(sweep(data, 2, mean.new[, i], FUN = '-')) %*% 
      ((sweep(data, 2, mean.new[, i], FUN = '-')) * post.prob[,i]) 
    tmp = tmp / sum(post.prob)
    sigma.new = sigma.new + tmp
  }
  
  return(list(prob = prob.new, mean = mean.new, Sigma = sigma.new))
}

myEM <- function(data, T, G, para){ 
  for(t in 1:T){
    post.prob <- Estep(data, G, para)
    para <- Mstep(data, G, para, post.prob) 
  }
  return(para) 
}
```

```{r}
n <- nrow(faithful)
Z <- matrix(0, n, 2)
Z[sample(1:n, 120), 1] <- 1
Z[, 2] <- 1 - Z[, 1]

ini0 <- mstep(modelName="EEE", faithful , Z)$parameters
# Output from my EM alg
para0 <- list(prob = ini0$pro, mean = ini0$mean, 
              Sigma = ini0$variance$Sigma)
myEM(data = faithful, T = 10, G = ncol(faithful), para = para0)

# Output from mclust
Rout <- em(modelName = "EEE", data = faithful, 
           control = emControl(eps=0, tol=0, itmax = 10), 
           parameters = ini0)$parameters
list(Rout$pro, Rout$mean, Rout$variance$Sigma)

```
The EM algorithm and its comparison with mclust package are shown above. Note that the results from my EM algorithm and the one from mclust are exactly the same. 

Please find the derivation of the E and M steps in the pdf file. 




